version: '3.4'
services:
  pwr-ingress:
    image: nginx:alpine
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  pwr-edge-service:
    image: docker.pkg.github.com/hbtgmbh/pwr-edge-service/pwr-edge-service:development
    restart: 'always'
    volumes:
      - pwr-log-files:/var/logs
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      zuuk_sensitive_headers: Cookie,Set-Cookie
      security_basic_enabled: 'false'
      security_headers_frame: 'true'
      spring_application_name: pwr-edge-service
      spring_http_multipart_max_file_size: 16MB
      spring_http_multipart_max_request_size: 16MB
      security_config_manager_dn: ${SECURITY_CONFIG_MANAGER_DN}
      security_config_manager_password: ${SECURITY_CONFIG_MANAGER_PASSWORD}
      security_config_user_search_base: ${SECURITY_CONFIG_USER_SEARCH_BASE}
      security_config_user_search_filter: ${SECURITY_CONFIG_USER_SEARCH_FILTER}
      security_config_group_search_base: ${SECURITY_CONFIG_GROUP_SEARCH_BASE}
      security_config_group_search_filter: ${SECURITY_CONFIG_GROUP_SEARCH_FILTER}
      security_config_role_prefix: ${SECURITY_CONFIG_ROLE_PREFIX}
      security_config_url: ${SECURITY_CONFIG_URL}
      eureka_client_service-url_defaultZone: http://pwr-discovery-service:8761/eureka
  pwr-discovery-service:
    image: docker.pkg.github.com/hbtgmbh/pwr-discovery-service/pwr-discovery-service:development
    ports:
      - "8761:8761"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    volumes:
      - pwr-log-files:/var/logs
  pwr_mariaDb:
    image: mariadb:latest
    restart: 'always'
    ports:
      - 9010:3306
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
  pwr_profile_service:
    image: docker.pkg.github.com/hbtgmbh/pwr-profile-service/pwr-profile-service:development
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      DB_USER: ${PROFILE_DB_USER}
      DB_PASS: ${PROFILE_DB_PASS}
      DB_URL: jdbc:mariadb://pwr_mariaDb:3306/profile
      DB_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      DB_HIBERNATE_DDL_AUTO: none
      EUREKA_ENABLED: 'true'
      EUREKA_URL: http://pwr-discovery-service:8761/eureka
      SERVER_PORT: 8080
    depends_on:
      - pwr_mariaDb
  pwr_webclient:
    image: docker.pkg.github.com/hbtgmbh/pwr-webclient/pwr-webclient:development
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      POWER_PROFILE_SERVICE_URL: http://power02.corp.hbt.de/api/pwr-profile-service
      POWER_SKILL_SERVICE_URL: http://power02.corp.hbt.de/api/pwr-skill-service
      POWER_VIEW_PROFILE_SERVICE_URL: http://power02.corp.hbt.de/api/pwr-view-profile-service
      POWER_REPORT_SERVICE_URL: http://power02.corp.hbt.de/api/pwr-report-service
      POWER_STATISTICS_SERVICE_URL: http://power02.corp.hbt.de/api/pwr-statistics-service
      POWER_LOCALE_PATH: http://power02.corp.hbt.de/localization
      POWER_IMAGE_PATH: /power/img
    volumes:
      - "/var/www/data/img/profile_pictures:/usr/share/nginx/html/img/profile_pictures"
  pwr-skill-service:
    image: docker.pkg.github.com/hbtgmbh/pwr-skill-service/pwr-skill-service:development
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      DB_USER: ${SKILL_DB_USER}
      DB_PASS: ${SKILL_DB_PASS}
      DB_URL: jdbc:mariadb://pwr_mariaDb:3306/skill
      DB_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      DB_HIBERNATE_DDL_AUTO: none
      EUREKA_ENABLED: 'true'
      # Assuming usage of the default docker-compose file provided with discovery.
      # Change if necessary
      EUREKA_URL: http://pwr-discovery-service:8761/eureka
    depends_on:
      - pwr_mariaDb
  pwr-view-profile-service:
    image: docker.pkg.github.com/hbtgmbh/pwr-view-profile-service/pwr-view-profile-service:development
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      DB_DATABASE: 4
      DB_PORT: 6379
      DB_HOST: view_profile_service_db
      SPRING_REDIS_PASSWORD: ${VIEW_PROFILE_DB_PASS}
      EUREKA_ENABLED: 'true'
      EUREKA_URL: http://pwr-discovery-service:8761/eureka
    depends_on:
      - view_profile_service_db
  view_profile_service_db:
    image: redis:alpine
    restart: 'always'
    command: redis-server --requirepass ${VIEW_PROFILE_DB_PASS}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    volumes:
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./rdb-data:/data"
  pwr_report_service:
    image: docker.pkg.github.com/hbtgmbh/pwr-report-service/pwr-report-service:development
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      DB_USER: ${REPORT_DB_USER}
      DB_PASS: ${REPORT_DB_PASS}
      DB_URL: jdbc:mariadb://pwr_mariaDb:3306/report
      DB_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      DB_HIBERNATE_DDL_AUTO: none
      EUREKA_ENABLED: 'true'
      EUREKA_URL: http://pwr-discovery-service:8761/eureka
      PWR_REPORT_FILE_PATH: /var/pwr
      LOGGING_LEVEL_DE_HBT: 'DEBUG'
    volumes:
      - ./report-data/datasource.xml:/var/pwr/xml/datasource.xml
      - /var/www/data/img/profile_pictures:/var/pwr/images # We need to mount the images because, for now, nginx has to deliver them, too
    depends_on:
      - pwr_mariaDb
  statistics:
    image: docker.pkg.github.com/hbtgmbh/pwr-statistics-service/pwr-statistics-service:development
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      DB_HOST: view_profile_service_db
      DB_PORT: 6379
      DB_DATABASE: 0
      DB_PASSWORD: ${VIEW_PROFILE_DB_PASS}
      EUREKA_ENABLED: 'true'
      EUREKA_URL: http://pwr-discovery-service:8761/eureka
  watchtower: #watchtower auto-updates our containers; It checks every 5 minutes.
    image: containrrr/watchtower
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      REPO_USER: ${GITHUB_REPO_USER}
      REPO_PASS: ${GITHUB_REPORT_PASS} # access token with permissions package=read
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pwr-log-files: {}
  db-data: {}